### ISSUE TITLE
 Missing Resources Bundle when Drag packaged framework to a project

### ISSUE THREAD

**Issue by Wilson2014** [CocoaPods/cocoapods-packager#144]
Hi man,

I need some help on below two questions as it's confusing me a lot time:

My framework contains a resource bundle defined in podspec using resource_bundles, after packed I can see a bundle with the name I specified in pod spec under generated framework properly. But when I drag the framework to a test project only the headers are included without the bundle,I have to drag the bundle to by project again. Is there a better way?

Second question, is the framework generated dynamic or static? is it possible to be refused by Apple review?

Thanks very much!

**Comment by neonichu** [comment]
There's a `--dynamic` option to generate a dynamic framework, the default is building static frameworks. In terms of app review, there's not really a difference between using a framework build by cp-packager and one you build using an Xcode target.

The issue you're seeing with resources is related: because static frameworks only exists at compile time, resources won't be part of your app — only dynamic frameworks support that feature.
