### ISSUE TITLE
Add support for `spec.vendored_{libraries,frameworks}`

### ISSUE THREAD

**Issue by mickeyreiss** [CocoaPods/cocoapods-packager#26]
If `vendored_libraries` or `vendored_frameworks` are specified in the podspec, they should be compiled into the generated static library just like source files.

**Comment by valentinogattuso** [comment]
I did some tests about this and as far as I understood neither vendored_frameworks nor vendored_libraries are merged into the final framework or library.

I created a framework from SSKeychain using "pod package SSKeychain.podspec --no-mangle"

LibA uses the SSKeychain.framework. [This][1] is the podspec. I created a framework from LibA using "pod package LibA.podspec --no-mangle" (note that I'm using a local version of the plugin that fixes #71)

As you can see [here][2] the symbol \_OBJC\_CLASS\_$\_SSKeychain is undefined.

To use the LibA.framework in a hosting app I need to link it with LibA.framework and SSKeychain.framework otherwise I get a linker error. 

I got the same result using SSKeychain as a static library.

I don't thing that vendored frameworks should be merged in the final framework or at least this should be configurable.

This is the scenario I'm currently working on.

* Pod ProductA
* Pod ProductB
* Pod CommonPlatform 

CommonPlatform contains services used by ProductA and ProductB and other functions that should be used by the hosting app (e.g. setup common API keys, login). ProductA and ProductB depend on CommonPlatform.framework so I don't want the CommonPlatform code to be merged into the product frameworks.

What do you think?

[1]:http://hastebin.com/raw/ebumejabek
[2]:http://hastebin.com/raw/cozatagime

**Comment by mickeyreiss** [comment]
For one of my use-cases, which is to compile a pod into a .a and headers for closed source release, we would like the vendored static library dependencies to be included in the final .a output.

**Comment by neonichu** [comment]
I think it makes total sense to :sparkles: vendor :sparkles:  the vendored libraries. Should possibly require passing `--no-mangle`, because the vendored library's symbols can't be mangled. In any case, not sure when I will get around to implementing it, so a PR would be awesome :heart:

**Comment by valentinogattuso** [comment]
I'm happy to help with PR. can you clarify the requirements? should the merging of vendored libraries and framework be the default behaviour? a flag?

On a side note, it should be possible to mangle the symbols of a pod dependency even if this pod dependency has a binary dependency because executing "nm -gU libPods-podDependency.a" won't return symbols defined in the binary dependency.

**Comment by neonichu** [comment]
I would say the default should be as it is now, bailing out with an error regarding binary dependencies. If `--no-mangle` is specified, vendored libraries are automatically lipo'ed into the result framework. For now, the build should probably also fail for dynamic libraries/frameworks as we cannot simply merge them.

**Comment by ploddi** [comment]
In fact, vendored static libraries and framework not automatically lipo'ed into the result framework. Probably related to https://github.com/CocoaPods/CocoaPods/issues/2926.

**Comment by neonichu** [comment]
@ploddi you're right, going back to my comment, it is pretty misleading, sorry. My intent was to describe how this could work once it was implemented, but it is not.

**Comment by ploddi** [comment]
Is there any quick hack to merge them into final framework?

**Comment by neonichu** [comment]
You could try looking for all static binaries inside the Pods directory and `lipo` them into the result.

**Comment by manuyavuz** [comment]
Solved by #194.
