### ISSUE TITLE
Create binaries from a given Podfile.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/cocoapods-packager#50]
Currently the packager only takes a single podspec, but it would be nice to be able specify a Podfile, if a user chooses to only want integrate binary products.

I think this could internally work the same in both scenarios, where you either use the specified Podfile or dynamically generate one that has the specified podspec as its dependency. Whether or not this makes things simpler or more complex is unknown to me right now.

**Comment by mdsb100** [comment]
@alloy 
+1
I am very excited.
We already do it.
Using cocoapods-packager to build binary.
podspec like this:
```
if ENV['IS_SOURCE'] || ENV["#{s.name}_SOURCE"]
    puts '-------------------------------------------------------------------'
    puts "Notice:#{s.name} is source now"
    puts '-------------------------------------------------------------------'
    s.source_files = "Pod/Classes/**/*.{h,m,mm}"
  else
    puts '-------------------------------------------------------------------'
    puts "Notice:#{s.name} is binary now"
    puts '-------------------------------------------------------------------'
    s.source_files = 'Pod/Products/include/**'
    s.public_header_files = 'Pod/Products/include/*.h'
    s.ios.vendored_libraries = "Pod/Products/lib/lib#{s.name}.a"
  end
```
Install:
```
IS_SOURCE=1 pod install
```
or
```
AFNetwork_SOURCE=1 pod install
```
The two questions is:
1. It must be in private repo, because there is json file in github repo and there is podspec file in private repo.
2. If I  am going to change pod between source and binary, I have to clean cache first and remove Pods/ dictionary.

If someone read Chinese, please check [this](http://www.yiqixiabigao.com/2016/07/15/ios-cocoapodszu-jian-ping-hua-er-jin-zhi-hua-fang-an-ji-xiang-xi-jiao-cheng/)


@neonichu 
When we do 'pod install', the project will rebuild. Even if we only change one pod`s version. Carthage can solve this trouble.
If CocoaPods@2.0 can support this feature, it can solve this trouble too. I am very happy to listen it.

**Comment by segiddins** [comment]
I think we can close this since Rome does this?

**Comment by neonichu** [comment]
@segiddins 👍
