### ISSUE TITLE
Category selectors are not mangled

### ISSUE THREAD

**Issue by neonichu** [CocoaPods/cocoapods-packager#52]
By default, the packager mangles class names, to avoid conflicts. As a user who depends on Pods which includes categories, one might also want a similar mangling to be applied to selectors provided by those categories. This is currently not done and cannot be achieved using the simple preprocessor based mangling that the packager uses.

**Comment by jtreanor** [comment]
This is something that I see as quite important. For example my framework includes AFNetworking, which has several categories on UIKit. This mean that users of my framework who also use AFNetworking will have build errors if they use any of the categories.

I would be happy to put work in to support this if it is at all possible but I must admit my understanding is lacking a little.
Is the reason that the preprocessor based mangling won't work because it is impossible to avoid mangling system selectors that are named the same as selectors in categories?

Is there another approach that could make sense?

**Comment by neonichu** [comment]
There is the problem with non-prefixed selectors that you mentioned, but also that even identifying category methods cannot be done using the approach that is taken right now. 

For your specific case, an idea would be to not depend on the UIKit subspec of AFNetworking if that is possible.

**Comment by jtreanor** [comment]
Thanks. That's what I will do for now. However, I still find it less than ideal that packager cannot support dependencies that have categories on system classes (which is quite common).

**Comment by neonichu** [comment]
I can understand that opinion. I'd totally be open to PRs to change the situation, it is just not something I'll personally concentrate on.

**Comment by jtreanor** [comment]
That's completely fair. I will continue to research it and if I come up with something I'll open a PR.

**Comment by blakewatters** [comment]
If you are developing a library that is intended (or can be reasonably expected) to be used as a dependency for other libraries then you really should be avoiding categories at all cost. There’s nothing achievable from a category that isn’t doable by other means — they are a convenience interface for app developers. C functions or static helper classes are preferable unless you are programming at the application level. 

Even in the rare instances that I expose any functionality via a category I tend to implement it in another unit and then just call into it from the category implementation.
