### ISSUE TITLE
Is it possible to package from local source?

### ISSUE THREAD

**Issue by jtreanor** [CocoaPods/cocoapods-packager#63]
The podspec I am packaging has a source line like this:

```
s.source = { :git => 'git@github.com:org/repo.git', :tag => s.version }
```

Packager does a great job of pulling that down and doing its magic.

However, for development, I would like to be able to build a framework from the local source. This would be really useful so that I can test things without having to pollute my repo with tags.

Is this something packager is capable of?

If not, perhaps a `--local` option could add this functionality.

**Comment by smistry-toushay** [comment]
+1

**Comment by neonichu** [comment]
This is related to #10 - I decided to stick with just one supported way of getting sources because of KISS.  

I think the best way to expand the current functionality would be to support two scenarios:

- `pod package AFNetworking`: Get the specification from the configured sources or master if none were specified, grab the files from wherever configured in the spec. That's the current use case of packaging a release, with the difference that you would not need a copy of the podspec file anymore.

- `pod package AFNetworking.podspec`: Use the local specification file and act as if using `:path => 'AFNetworking.podspec'` in the Podfile. That would support the local development use case.

Also related are #49 and #35

**Comment by neonichu** [comment]
Changes need for that:

- Fix `spec_for_name`, used here: <https://github.com/CocoaPods/cocoapods-packager/blob/master/lib/pod/command/package.rb#L38>

- Change <https://github.com/CocoaPods/cocoapods-packager/blob/master/lib/cocoapods-packager/pod_utils.rb#L23> so that it uses a Podfile without any arguments for the first case and `:path` for the second case

**Comment by kylef** [comment]
@neonichu In my original notes on how the packager should work (in #1) was something like this:

```
$ pod lib package
$ pod spec package
```

So it would be consistent with the behaviour of the other pod commands operating on specs.

**Comment by XBeg9** [comment]
Any updates?

**Comment by ZuhanLin** [comment]
Any updates?

**Comment by segiddins** [comment]
Nope, this is still waiting on someone to make a pull request.

**Comment by ZuhanLin** [comment]
Oh?  I use path like this : s.source: path = >'~/Desktop/MyFramework.zip'  ,  then pod install , i found it  working.  So  maybe someone  fix it?

**Comment by manuyavuz** [comment]
Solved by #194.

**Comment by karosLi** [comment]
it is not work for me, I am using cocoapods-packager 1.5.0 based on cocoapods 1.3.1

**Comment by radvansky-tomas** [comment]
How exactly it this solved ? What arguments We have to add for locally developed podspec?

**Comment by manuyavuz** [comment]
`pod package --local /path/to/your/local/podspec/file.podspec`

**Comment by acruis** [comment]
For those whom `pod package --local` produces ``[!] Unknown option: `--local` `` and found  this issue:
The latest version (1.5.0) was published in 2016, while #194 was in 2018.

Add your +1s to request new version release here: https://github.com/CocoaPods/cocoapods-packager/issues/200

**Comment by hmertkahraman** [comment]
+1

**Comment by ryango** [comment]
can install from master by doing
gem install specific_install
gem specific_install https://github.com/CocoaPods/cocoapods-packager
to pick up the --local option in the meantime
