### ISSUE TITLE
Package should include Bitcode

### ISSUE THREAD

**Issue by jtreanor** [CocoaPods/cocoapods-packager#98]
After updating to Xcode 7 GM, packager still works great (:smile:).

One notable exception is that there is no bitcode included in the resulting framework. This leads to the issue discussed on SO [here](http://stackoverflow.com/questions/31486232/how-do-i-xcodebuild-a-static-library-with-bitcode-enabled).

For now I am working around this by adding this line to my podspec:

```
s.pod_target_xcconfig = { 'OTHER_CFLAGS' => '-fembed-bitcode' }
```

However, I think packager should include built in support for this, since it is on by default in Xcode 7.

I will try to take the time to write up a PR later in the week. Its proving a little trickier than I originally thought.

**Comment by neonichu** [comment]
This makes sense, let me know if I can help with the PR.

**Comment by segiddins** [comment]
If the packager does an archive build, `xcodebuild` should handle this automatically.

**Comment by jtreanor** [comment]
@segiddins Yeah, that could possibly be a better approach.

**Comment by jtreanor** [comment]
I have opened a PR in #100. There is one persistent issue that I can't quite figure out.

**Comment by rgal75** [comment]
@jtreanor I am also facing this bitcode issue. I applied the workaround you mentioned above but it only includes bitcode in my library. However, my library has a Pod dependency (AFNetworking) and the application I am linking against my library complains upon archiving that:
`ld: bitcode bundle could not be generated because '/Users/xxx/work/MyApp/MyLib.framework/MyLib(AFHTTPRequestOperationManager.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

Do you have a workaround for this case?

Will your cocoapods-packager solution in PR #100 handle this case?

**Comment by jtreanor** [comment]
@rgal75 yes, the changes I made should address this (I am using AFNetworking without issue).
